### ISSUE TITLE
How to use data converter without using Laravel? 

### ISSUE THREAD

**Issue by BadPistol97** [MotivoZwolle/editorjs-data-converter#19]
How to use data converter in Apache PHP? I am confused. 

My attempt: 
` 
           
                       <?php 

                        require 'C:\xampp\composer\vendor\autoload.php';

                        use Motivo\EditorJsDataConverter\DataConverter;
                        use Motivo\EditorJsDataConverter\Collections\RegisteredConverters;

                       if(!empty($_POST)){
                              if(isset($_POST["output"])){
                                      $output = (new DataConverter(new RegisteredConverters()))->init($_POST["output"]);
                              echo "ok";
                           }
                      }

                    else
                     echo"no empty";

                    ?>`
 
`

**Comment by wotta** [comment]
The package was made to be used in Laravel. it uses the boot and register methods of the service providers so it is difficult to use this package without Laravel.

Did you look through the code to see how it works? Because there should be a way to register the converters. Otherwise, the converter will not do anything.

**Comment by BadPistol97** [comment]
Okay, thanks.
